### ISSUE TITLE
Suggestions for the Top Toolbar and left hand panel on book page

### ISSUE THREAD

**Issue by kaiThomas236** [wavemakercards/wavemaker-cards-v4#20]
Hiya, this is less of an issue and more of a suggestion. currently, the upper navbar area overflows the page and causes a persistent horizontal scroll bar which I am not a fan of. This is caused by the little tool pop-up text things that appear when you hover over the buttons. I made a local override for my system that resolves it as follows:

```
.toolbarButton:nth-child(3) .tooltiptext {
    right: 60px;
}
.toolbarButton:nth-child(4) .tooltiptext {
    right: 15px;
}
span .toolbarButton span.tooltiptext {
    right: 15px;
}
```

I think it would be even better if these html elements were given unique identifiers, then they could be accessed in a more consistent and reliable way, rather than the nth-child thing I'm doing here (I can't figure out how to override html files). with my solution they get a bit misaligned when the google drive save button is visible, but it still prevents that horizontal scroll bar.

also, on the main book page with the text box and everything, I think the left hand side .scrollpanel element should have padding added to the bottom equivalent to the height of one of the files or folders. the last file or folder in the list always seems impossible to get to for me otherwise. right now I have added:

`padding-bottom: 45px;`

to the two instances which had no bottom padding originally, and it resolves that issue. 

anyway, I hope I'm not stepping on any toes here, just some little things I noticed as someone at the cross section of web development and writing. love this program overall :)

Thanks!

**Comment by wavemakercards** [comment]
Dev branch has changes that implement this - so will be in play soon
