### ISSUE TITLE
Unaccessible section/folders

### ISSUE THREAD

**Issue by Samo276** [wavemakercards/wavemaker-cards-v4#22]
Using win10 and installed wavemaker using edge browser.

Error occurs when you have filled section/folder tree, after you reach the end of screen, the new folder/section you create (call it A) is outside of your screen and you cannot scroll down to click on it, if you create another one (call it B), the "another one (B)" is outside of screen, but you can scroll up to the previous one (A). If you can colapse folders you can force the B to apear but if you whole tree is covered in folders there is no way of accesing the last one created.
![wmc4bug](https://github.com/wavemakercards/wavemaker-cards-v4/assets/33495575/c218d770-a9de-49e6-8486-c8c7ca0fe2a8)

**Comment by wavemakercards** [comment]
I have made a tweak that should remove this issue
